<a href="https://colab.research.google.com/github/Nouman-wisal/pytorch/blob/main/00_pytorch_vedio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello i'm starting to learn pytorch today 17-may-2025")

hello i'm starting to learn pytorch today 17-may-2025


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
#scalar
scalar=torch.tensor(5)
scalar
# scalar.ndim
# scalar.shape
# scalar.item() #to convert the tensor/scalar back to python int


tensor(5)

In [ ]:
# Vector

vector=torch.tensor([1,2,3],dtype=None, device=None,requires_grad=False)
vector
vector.ndim
# vector.shape

1

In [ ]:
# MATRIX

MATRIX=torch.tensor([[1,2,3],
                    [4,5,6]])
MATRIX
MATRIX.ndim
MATRIX.shape

torch.Size([2, 3])

In [ ]:
#TENSOR1

TENSOR=torch.tensor([
    [[1,2,3],
    [4,5,6]],

    [[11,12,13],
     [14,15,16]]
])

TENSOR
TENSOR.ndim
TENSOR.shape
TENSOR[1]

tensor([[11, 12, 13],
        [14, 15, 16]])

In [ ]:
#TENSOR2
TENSOR2=torch.tensor([[[78,34,56],
                       [32,54,13],
                        [98,63,21]]])
TENSOR2
TENSOR2.ndim
TENSOR2.shape
TENSOR2[0]

tensor([[78, 34, 56],
        [32, 54, 13],
        [98, 63, 21]])

##RANDOM TENSORS
why random tensors?

the way many neural networks learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers `

In [ ]:
# CREATING RNDOM TENSOR
random_tensor=torch.rand(4,4)
random_tensor

tensor([[0.9929, 0.2535, 0.1790, 0.1465],
        [0.5386, 0.9760, 0.8070, 0.5371],
        [0.2666, 0.1884, 0.8700, 0.6341],
        [0.9104, 0.4559, 0.1255, 0.0643]])

In [ ]:
random_tensor1= torch.rand(3,3,4)
random_tensor1
random_tensor1.ndim,random_tensor1.shape


(3, torch.Size([3, 3, 4]))

#Creating a random tensor in shape of an image tensor

In [ ]:
# random image size tensor

rand_image_size_tensor = torch.rand(size=(3,224,224))

rand_image_size_tensor.shape,rand_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [ ]:
# creating tensor with zeros
zeros_tensor= torch.zeros(4,4)

zeros_tensor.dtype,zeros_tensor

zeros_tensor * random_tensor


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# creating tensors with ones
ones_tensor=torch.ones(2,2)

ones_tensor, ones_tensor.dtype

(tensor([[1., 1.],
         [1., 1.]]),
 torch.float32)

#Creating arange tensor

In [ ]:
arange_tensor= torch.arange(0,10,2)

arange_tensor , arange_tensor.dtype,arange_tensor.ndim


(tensor([0, 2, 4, 6, 8]), torch.int64, 1)

In [ ]:
# creating tensors like. meaning in the shape of any tensor given as input

zeros_like= torch.zeros_like(input= arange_tensor) #imp
zeros_like

# ones_like=torch.ones_like(input=arange_tensor)
# ones_like

# random_like=torch.rand_like(input=arange_tensor , dtype=torch.float32)
# random_like

tensor([0, 0, 0, 0, 0])

#Tensors data types
tensor datatypes is one of the 3 big errors you will run into in macine learning and deep learning
1. Tensor not right datatype
2. Tensor not right shape
3.Tensor not right device


In [ ]:
float32_tensor= torch.tensor([3.0,6.0,9.0], dtype=None,                        # what is the datatype of your tensor "float16" or "float32"
                                               device=None,                             # what device is your tensor on "cpu" or "GPU"
                                               requires_grad=False)                     # whether or not to trace gradient with tensors operations
float32_tensor.dtype

torch.float32

In [ ]:
# converting data type of tensors
# from float32 (default/single precision) to torch.float16 /half precision

float16_tensor= float32_tensor.type(torch.float16) #imp
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
check=float32_tensor * float16_tensor

check , check.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [ ]:
int32_tensor= torch.tensor([2,4,6],dtype=torch.int64)

check1 = float32_tensor * int32_tensor
check1 , check1.dtype

(tensor([ 6., 24., 54.]), torch.float32)

###Getting information from tensor (Tensor Attribute)


1.   Tensor not right data type , to get datatype of tensor `torch.dtype`
2.   Tensor not right shape , to get shape of tensor `torch.shape` or `torch.size()`  

1.   Tensor not on right device , to get device of tensor `torch.device`







In [ ]:
# creating random tensor with all attributes

Tensor_attributes= torch.rand(4,5,dtype=torch.float16, device=torch.device("cpu"), requires_grad=False)

print(Tensor_attributes)
print(f"\nThe shape of the tensor is    '{Tensor_attributes.shape}'")
print(f"The datatype of thetensor is    '{Tensor_attributes.dtype}'")
print(f"The device on which tensor is   '{Tensor_attributes.device}'")

tensor([[0.8540, 0.3374, 0.2393, 0.3770, 0.6968],
        [0.8232, 0.1045, 0.4463, 0.6562, 0.2959],
        [0.0469, 0.6548, 0.9282, 0.1978, 0.7539],
        [0.5259, 0.8672, 0.6006, 0.5317, 0.5693]], dtype=torch.float16)

The shape of the tensor is    'torch.Size([4, 5])'
The datatype of thetensor is    'torch.float16'
The device on which tensor is   'cpu'


##Matrix operations (+ , - , / , multiply but it has two different types)

In [ ]:
tensor= torch.tensor([1,2,3])

# addition in tensors
tensor + 10 , tensor + tensor
# or
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
# subtraction in tensors

tensor - 10 , tensor - tensor
# or
torch.subtract(tensor,10)

tensor([-9, -8, -7])

In [ ]:
# division in tensor

tensor / 2
# or
torch.div(tensor,2)

tensor([0.5000, 1.0000, 1.5000])

# The two two types of multiplication are :


1.   Element wise Multiplication
2.   Matrix Multiplication or aka Dot Product



In [ ]:
# element wise multiplication
# it'll multiply the scalar int with all every number in matrix/vector

element_wise= tensor * 3
element_wise
# or
torch.mul(tensor,3) #imp

tensor([3, 6, 9])

In [ ]:
# matrix multiplication

dot_matrix= torch.matmul(tensor,tensor)
dot_matrix


tensor(14)

## Matrix multiplication has two rules:


1.   inner dimension must match i.e (2,3) @ (3,4) not (2,3) @ (4,2)
2.   the resulting matrix will have the shape of outer dimension i.e upper shape will be ==> size([4,4])



In [ ]:
# matmul

matmult= torch.matmul(torch.rand(4,3) , torch.rand(3,5))

matmult , matmult.shape

(tensor([[0.4560, 0.7714, 0.4922, 0.7963, 0.6943],
         [0.5841, 0.5430, 0.1661, 1.0388, 0.4711],
         [1.0087, 1.3989, 0.7298, 1.8175, 1.2485],
         [0.6651, 0.7671, 0.2173, 1.3202, 0.6821]]),
 torch.Size([4, 5]))

In [ ]:
                                                            # TRANSPOSE
# FIXING THE INNER DIMENSION OF TENSOR IF NOT RIGHT WITH TRANSPOSE

tensor_A = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

tensor_B= torch.tensor([[10,11,12],
                        [13,14,15]])

tensor_A.shape , tensor_B.shape # inner dimensions doesnt match (3,3),(2,3) it should be (3,3)

print("shape of tensor B after transpose \n\n",tensor_B.T.shape)  # transpose of B
print(tensor_B.T)

torch.matmul( tensor_A , tensor_B.T )


shape of tensor B after transpose 

 torch.Size([3, 2])
tensor([[10, 13],
        [11, 14],
        [12, 15]])


tensor([[ 68,  86],
        [167, 212],
        [266, 338]])

##Aggregating tensors `( min ,max, mean , sum, argmin, argmax)`

In [ ]:
# min ,max , sum

tensor_x= torch.arange(10,100,10)
tensor_x

# min ,max , sum
torch.min(tensor_x) , torch.max(tensor_x) , torch.sum(tensor_x) # prefered
# or
tensor_x.min() , tensor_x.max() , tensor_x.sum()

(tensor(10), tensor(90), tensor(450))

In [ ]:
# argmin, argmax()

torch.argmin(tensor_x) , torch.argmax(tensor_x), tensor_x[0] , tensor_x[8]

(tensor(0), tensor(8), tensor(10), tensor(90))

In [ ]:
# argmin, argmax()

matrix_x = torch.tensor([[1, 7],
                         [4, 3]])

print("Argmax:", torch.argmax(matrix_x))  # Flattened: [1, 7, 4, 3] → max is 7 at index 1
print("Argmin:", torch.argmin(matrix_x))  # min is 1 at index 0

# print("\nfinding argmin and arg max column_row_wise\n")

# print("Argmax (dim=0):", torch.argmax(matrix_x, dim=0))  # Compare column-wise
# print("Argmax (dim=1):", torch.argmax(matrix_x, dim=1))  # Compare row-wise


Argmax: tensor(1)
Argmin: tensor(0)


In [ ]:
# mean
# for mean datatype must be chnage to float32 or complexdtype

torch.mean( tensor_x.type(torch.float32) ) #prefered
# or
tensor_x.type(torch.float32).mean()

tensor(50.)

##`Reshape` : reshapes the input tensor to a defined shape. adds a dimension `[]` too
##`View` : does the same thing`syntax is bit different` as "reshaping" but to the original tensor bcz it shares the same memory
##`Stacking` : combines multiple tensors on top of eachother, `vstack` or sideby side `hstack`
##`Squeeze` : remove all 1 dimension from tensor
##`Unsqueeze` : add 1 dimension to the target tensor
##`Permute` : returns a view of input with dimension permuted(swapped) in a certain way.

In [ ]:
# reshapiing the tensor

tensor_n= torch.arange(1.,10.)
print( tensor_n , tensor_n.shape , "\n" )

reshape_n = torch.reshape (tensor_n, (1,9))    # bcz resultig matrix will have the shape(no of cols) of outer dimension aka 9 (col) asmentioned
#or reshape_n = tensor_n.reshape (1,9)
print(reshape_n,"\n")

reshape_n1= torch.reshape(tensor_n, (9,1)) # not printing bcz it's long
#or reshape_n1 = tensor_n.reshape (9,1)
# print(reshape_n1,"\n")    # bcz resultig matrix will have the shape(no of cols) of outer dimension aka 1 (col) asmentioned

reshape_n2 = torch.reshape(tensor_n , (3,3))
#or reshape_n2 = tensor_n.reshape (3,3)
reshape_n2

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9]) 

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) 



tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# view(change in the original tensor bcz it shares same memory) the tensor
# torch.view wont work, have to used org var name like tensor_k

tensor_k= torch.arange(1,30,2)
print( tensor_k.shape , tensor_k , "\n" )

view_k= tensor_k.view(5,3)
view_k
# view_k[:,0]=5 just fyi it means all slect all rows of first col and change them to 5



torch.Size([15]) tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]) 



tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17],
        [19, 21, 23],
        [25, 27, 29]])

##combining matrices and vectors
###torch.stack , torch.vstack , torch.hstack


In [ ]:
tensr_1= torch.tensor([[1,2,3],
                     [4,5,6]])

tensr_2= torch.tensor([[7,8,9],
                      [10,11,12]])

stack_0 = torch.stack((tensr_1 , tensr_2 ),dim=0) # it'll combine two matrixs row wise and in 3dim unlike v&hatack
stack_1 =torch.stack((tensr_1 , tensr_2),dim=1) # it'll also combine but first rows of both tensors first in first matrix and second rows in second matrix

print("stack with dim=0\n",stack_0 , stack_0.shape ,"\n")
print("stack with dim=1\n",stack_1 , stack_1.shape ,"\n")

stack with dim=0
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) torch.Size([2, 2, 3]) 

stack with dim=1
 tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]]) torch.Size([2, 2, 3]) 



In [ ]:
A= torch.tensor([1,2,3])
B= torch.tensor([4,5,6])

torch.stack((A,B),dim=0) , torch.stack((A,B),dim=1)


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [ ]:
# vstack hstack with vectors
print( A , B ,"\n")

vstack = torch.vstack((A,B,A))
hstack = torch.hstack((A,B,A))

print(vstack , "\n")
print(hstack)


tensor([1, 2, 3]) tensor([4, 5, 6]) 

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]]) 

tensor([1, 2, 3, 4, 5, 6, 1, 2, 3])


In [ ]:
# vstack hstack with matrix , they wont create 3rd dim unlike stack with dim=0or1 instead it'll make it one matrix
print(tensr_1 , "\n")
print(tensr_2, "\n")

vstack1 = torch.vstack((tensr_1 , tensr_2))
hstack1= torch.hstack((tensr_1 , tensr_2))

print(vstack1 , "\n")
print(hstack1)

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor([[ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) 

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


##Squeeze & Unsqueeze

In [ ]:
# SQUEEZE removes all dimensions of 1 from tensor

before_tens = torch.zeros(2,3,1,3,1)
print("shape before squeezing \n",before_tens.shape,"\n")

after_tens= torch.squeeze(before_tens)
print("shape after squeezing \n",after_tens.shape,"\n") # removes all dimensions of 1

x = torch.tensor([[[2,2,1,4,1]]])
print("shape before squeezing \n", x.shape,"\n")

y = torch.squeeze(x)
print("shape after squeezing \n",y.shape,"\n")




shape before squeezing 
 torch.Size([2, 3, 1, 3, 1]) 

shape after squeezing 
 torch.Size([2, 3, 3]) 

shape before squeezing 
 torch.Size([1, 1, 5]) 

shape after squeezing 
 torch.Size([5]) 



In [ ]:
# UNSQUEEZE add dimension to target tensor

a = torch.tensor([3,4,5])

print("tensor a \n", a, "\n")
print("shape before unsqueeze \n", a.shape,"\n")

b = torch.unsqueeze(a , dim=0)

print("shape after unsqueeze \n",b.shape,"\n")
print("tenosr b\n",b , "\n")

c= torch.unsqueeze(a, dim=1)

print("shape after unsqueeze \n",c.shape,"\n")
print("tenosr b\n",c , "\n")



tensor a 
 tensor([3, 4, 5]) 

shape before unsqueeze 
 torch.Size([3]) 

shape after unsqueeze 
 torch.Size([1, 3]) 

tenosr b
 tensor([[3, 4, 5]]) 

shape after unsqueeze 
 torch.Size([3, 1]) 

tenosr b
 tensor([[3],
        [4],
        [5]]) 



##Permute
torch.permute(input, dims) → Tensor
Returns a view of the original tensor input with its dimensions permuted(altered).

In [ ]:
# permuting tensor
input_tensor = torch.randn(2,3,4)
print("input_tensor :\n",input_tensor)
print("\ninput_tensor shape:\n",input_tensor.shape)

permutated_tensor= torch.permute(input_tensor,(1,2,0))
print("\npermutated tensor with changed dims\n", permutated_tensor)
print("\npermutated_tensor shape:\n",permutated_tensor.shape)



input_tensor :
 tensor([[[-1.3533,  0.0751, -0.1868, -0.0433],
         [ 1.2911,  0.0666,  1.0287, -1.0481],
         [ 0.1170,  0.1920, -0.6608, -0.7589]],

        [[ 0.8452, -0.1112, -0.2244, -0.6014],
         [ 0.8455, -0.4959, -1.3464,  0.4992],
         [ 0.4181, -0.7920,  0.9848,  0.6285]]])

input_tensor shape:
 torch.Size([2, 3, 4])

permutated tensor with changed dims
 tensor([[[-1.3533,  0.8452],
         [ 0.0751, -0.1112],
         [-0.1868, -0.2244],
         [-0.0433, -0.6014]],

        [[ 1.2911,  0.8455],
         [ 0.0666, -0.4959],
         [ 1.0287, -1.3464],
         [-1.0481,  0.4992]],

        [[ 0.1170,  0.4181],
         [ 0.1920, -0.7920],
         [-0.6608,  0.9848],
         [-0.7589,  0.6285]]])

permutated_tensor shape:
 torch.Size([3, 4, 2])


In [ ]:
# permute image tensor, permute also share same memory with org tensor like org_img

org_img = torch.rand(size=(224,224,3)) # height , width , color_channel

print("\nshape of org img before permute:\n", org_img.shape, "\n")

edit_img= torch.permute(org_img, (2,1,0))

print("shape of org img after permute:\n", edit_img.shape, "\n")


shape of org img before permute:
 torch.Size([224, 224, 3]) 

shape of org img after permute:
 torch.Size([3, 224, 224]) 



##Indexing

In [ ]:
tensr_indexing= torch.arange(1,21).reshape(1,5,4)

print(tensr_indexing,"\n")
# print("\n", tensr_indexing.shape)

print(tensr_indexing[0])      # it'll give the whole matrix bcz it's inside the tensor at position 0
print(tensr_indexing[0,0])    #it'll give the first row only
print(tensr_indexing[0,0,0] )  #it'll give the first value only

tensr_indexing[0,0,0] = 100
print(tensr_indexing[0,0,0] )  # changing a specific value in matrix


tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16],
         [17, 18, 19, 20]]]) 

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])
tensor([1, 2, 3, 4])
tensor(1)
tensor(100)


In [ ]:
print(tensr_indexing,"\n")

print("indexing only first 2 cols but all rows\n", tensr_indexing[:, :, 0:2])

print("\nindexing only first 2 cols & 3 rows\n", tensr_indexing[0, 0:3, 0:2])

print("\nindexing the third column only\n", tensr_indexing[:, : , 2])

print("\nindexing the first row only\n", tensr_indexing[0, 0, :])

tensor([[[100,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12],
         [ 13,  14,  15,  16],
         [ 17,  18,  19,  20]]]) 

indexing only first 2 cols but all rows
 tensor([[[100,   2],
         [  5,   6],
         [  9,  10],
         [ 13,  14],
         [ 17,  18]]])

indexing only first 2 cols & 3 rows
 tensor([[100,   2],
        [  5,   6],
        [  9,  10]])

indexing the third column only
 tensor([[ 3,  7, 11, 15, 19]])

indexing the first row only
 tensor([100,   2,   3,   4])


##Numpy to Pytorch & viceversa

In [ ]:
# np --> pytorch
#imp --> dafault dtype in tensor is float but in array is float64

array= np.arange(1.,10.).reshape(3,3)
print("np array and default it's data type\n",array,"\n",array.dtype)

tensar=torch.from_numpy(array)
print("\n converted to tensor & default dtype right after conversion\n",tensar)

tensar= tensar.type(torch.float32)
print( "\n",tensar +1 )

tensar.dtype , array.dtype          # chnging the dtype of tensar wont effect the default dtype of array



np array and default it's data type
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 
 float64

 converted to tensor & default dtype right after conversion
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

 tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])


(torch.float32, dtype('float64'))

In [ ]:
# Pytorch --> numpy

# tensaar= torch.ones(10).reshape(2,5) or
tensaar= torch.ones(2,5)
print(tensaar,tensaar.dtype, "\n")

to_numpy= tensaar.numpy()
print(to_numpy , to_numpy.dtype ,"\n" )

to_numpy +1,tensaar                     #same rule as above applies regarding dtypes and chnages later on(which won't effect org)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) torch.float32 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float32 



(array([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=float32),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]))